# Site wide configuration

title:            Bonvin Lab
locale:           en_US
url:              http://haddocking.github.io

# RSS Feed configuration
name: Bonvin Lab
description: Webpage of the computational structural biology lab of Alexandre Bonvin
rss: true

# Jekyll configuration
permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


# Site owner
owner:
  name: Alexandre Bonvin
  avatar: bio-haddock.png
  bio: "Computational Structural Biology group focusing on dissecting, understanding and predicting biomolecular interactions at the molecular level."
  email: a.m.j.j.bonvin@uu.nl
  youtube: haddocking
  google:
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  github: haddocking

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "_utilities"]
